# Generated by Django 3.2 on 2022-08-15 13:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=50)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
