# Generated by Django 3.2 on 2022-08-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Featured_Company',
        ),
        migrations.AddField(
            model_name='featuredcompany',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.featuredpicture'),
        ),
    ]
