# Generated by Django 3.2 on 2022-08-15 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220815_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpicture',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
