# Generated by Django 3.2 on 2022-08-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_featuredpicture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcompany',
            name='picture',
        ),
    ]
