# Generated by Django 3.2 on 2022-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_featuredcompany_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpicture',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
