# Generated by Django 3.2 on 2022-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_featuredpicture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpicture',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='featuredpicture',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='featuredpicture',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
