# Generated by Django 3.2 on 2022-08-16 11:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220816_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcompany',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='featuredcompany',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcompany',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcompany',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcompany',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
