# Generated by Django 3.2 on 2022-08-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220816_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpicture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='featuredpicture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featuredpicture',
            name='location',
        ),
        migrations.RemoveField(
            model_name='featuredpicture',
            name='name',
        ),
        migrations.AlterField(
            model_name='featuredcompany',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.featuredpicture'),
        ),
    ]
