# Generated by Django 3.2 on 2022-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(0, 'A6'), (1, 'A5'), (2, 'A4')]),
        ),
    ]
