# Generated by Django 3.2 on 2022-08-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
