# Generated by Django 3.2 on 2022-08-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
