# Generated by Django 3.2 on 2022-08-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220816_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredcompany',
            options={'verbose_name_plural': 'Featured companies'},
        ),
    ]
