# Generated by Django 3.2 on 2022-08-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_shopdescription_shoppicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpicture',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='shoppicture',
            name='picture',
        ),
        migrations.AddField(
            model_name='featuredpicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='featuredpicture',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='shoppicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shoppicture',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
