# Generated by Django 3.2 on 2022-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220818_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcompany',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='shopdescription',
            name='picture',
        ),
        migrations.AddField(
            model_name='featuredcompany',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='featuredcompany',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='shopdescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shopdescription',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='FeaturedPicture',
        ),
        migrations.DeleteModel(
            name='ShopPicture',
        ),
    ]
