# Generated by Django 3.2 on 2022-08-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
