# Generated by Django 3.2 on 2022-08-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
