# Generated by Django 3.2 on 2022-08-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(choices=[(0, '100'), (1, '250'), (2, '500'), (3, '1000'), (4, '2500')])),
                ('lamination', models.IntegerField(choices=[(0, 'Matt'), (1, 'Gloss'), (2, 'Soft Touch, Velvet')])),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AddField(
            model_name='businesscards',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.picture'),
        ),
    ]
