# Generated by Django 3.2 on 2022-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220816_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, choices=[(0, 'A5'), (1, 'A6'), (2, 'A4'), (3, '148mm x 148mm'), (3, 'DL')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='laminate',
            field=models.IntegerField(blank=True, choices=[(0, 'Matt'), (1, 'Gloss'), (2, 'Soft Touch')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, choices=[(0, '100'), (1, '250'), (2, '500'), (3, '1000'), (4, '2500'), (5, '5000')], null=True),
        ),
    ]
