# Generated by Django 3.2 on 2022-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='65.00', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, choices=[(0, '100'), (1, '250'), (2, '500'), (3, '1000'), (4, '2500'), (5, '5000')], default='100', null=True),
        ),
    ]
