# Generated by Django 3.2 on 2022-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220817_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, choices=[(0, '100'), (1, '250'), (2, '500'), (3, '1000'), (4, '2500'), (5, '5000')], null=True),
        ),
    ]
